name: 'pkg-config'
version: 0.29.2 
url: 'https://pkg-config.freedesktop.org/releases'
ext: tar.gz
depends: [base/glibc, lib/glib]
fix_ldflags: true
toolchain: true
toolchain_disable_nls: true
toolchain_disable_shared: true
toolchain_enable_static: true
toolchain_autoconf_args:
- '--with-internal-glib'
source_file_sha256: '6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591'
